/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import crud.crudfasilitas;


public class fasilitas extends javax.swing.JFrame {
    crudfasilitas Fasilitas;

    public fasilitas() {
        initComponents();
        Fasilitas = new crudfasilitas (this);
        Fasilitas.isitable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Createbtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        Exitbtn = new javax.swing.JButton();
        Searchbtn = new javax.swing.JButton();
        searchtxt = new javax.swing.JTextField();
        idtxt = new javax.swing.JTextField();
        cbjenis = new javax.swing.JComboBox<>();
        namatxt = new javax.swing.JTextField();
        kapasitastxt = new javax.swing.JTextField();
        cbstatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modeltabelfasilitas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Createbtn.setText("CREATE");
        Createbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Createbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        Updatebtn.setText("UPDATE");
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        Deletebtn.setText("DELETE");
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        Exitbtn.setText("EXIT");
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        Searchbtn.setText("SEARCH");
        Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        searchtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtxtActionPerformed(evt);
            }
        });
        getContentPane().add(searchtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 300, 220, -1));
        getContentPane().add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 80, -1));

        cbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---jenis fasilitas---", "lapangan", "lainnya", " " }));
        cbjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjenisActionPerformed(evt);
            }
        });
        getContentPane().add(cbjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));
        getContentPane().add(namatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 150, 30));
        getContentPane().add(kapasitastxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 100, -1));

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---ketersedian---", "Available", "Not Available" }));
        getContentPane().add(cbstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\PBO\\src\\main\\java\\image\\fasilitas (1).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        modeltabelfasilitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Jenis", "Nama Fasilitas", "Kapasitas", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        modeltabelfasilitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modeltabelfasilitasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(modeltabelfasilitas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 600, 260));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void CreatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatebtnActionPerformed
        Fasilitas.create();
        Fasilitas.isitable();
        Fasilitas.reset();
    }//GEN-LAST:event_CreatebtnActionPerformed

    private void cbjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbjenisActionPerformed

    private void SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbtnActionPerformed

        Fasilitas.cariNama();
    }//GEN-LAST:event_SearchbtnActionPerformed

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
       Fasilitas.update();
       Fasilitas.isitable();
       Fasilitas.reset();
    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        Fasilitas.delete();
        Fasilitas.isitable();
        Fasilitas.reset();
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
        menu menu = new menu();
        menu.setVisible(true);
    }//GEN-LAST:event_ExitbtnActionPerformed

    private void modeltabelfasilitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modeltabelfasilitasMouseClicked
        Fasilitas.isiField(modeltabelfasilitas.getSelectedRow());
    }//GEN-LAST:event_modeltabelfasilitasMouseClicked

    private void searchtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtxtActionPerformed
    
    }//GEN-LAST:event_searchtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fasilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fasilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fasilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fasilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fasilitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Createbtn;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JButton Exitbtn;
    private javax.swing.JButton Searchbtn;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JComboBox<String> cbjenis;
    private javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kapasitastxt;
    private javax.swing.JTable modeltabelfasilitas;
    private javax.swing.JTextField namatxt;
    private javax.swing.JTextField searchtxt;
    // End of variables declaration//GEN-END:variables
    
    public JButton getSearchbtn() {
        return Searchbtn;
    }
    
    public JButton getCreatbtn() {
        return Createbtn;
    }
    
    public JButton getUpdatebtn() {
        return Updatebtn;
    }
    
    public JButton getDeletebtn() {
        return Deletebtn;
    }
    
    public JButton getExitbtn() {
        return Exitbtn;
    }
    
    public JTable getTabelFasilitas() {
        return modeltabelfasilitas;
    }
    
    public JTextField getsearchtxt() {
        return searchtxt;
    }
    
    public JTextField getTxtId() {
        return idtxt;
    }
    
    public JComboBox<String> getcbjenis() {
        return cbjenis;
    }
    
    public JTextField getnamatxt() {
        return namatxt;
    }
    
    public JTextField getkapasitastxt() {
        return kapasitastxt;
    }
    
    public JComboBox<String> getcbstatus() {
        return cbstatus;
    }
}
