/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import crud.crudpeminjaman;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

public class peminjaman extends javax.swing.JFrame {
    crudpeminjaman Peminjaman;

    
    public peminjaman() {
        initComponents();
        Peminjaman = new crudpeminjaman (this);
        Peminjaman.isitable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtId = new javax.swing.JTextField();
        TglWaktuFormat = new javax.swing.JFormattedTextField();
        catatan = new javax.swing.JScrollPane();
        Catatantxt = new javax.swing.JTextArea();
        Createbtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();
        Exitbtn = new javax.swing.JButton();
        Caritxt = new javax.swing.JTextField();
        Searchbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modeltabelpeminjaman = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdActionPerformed(evt);
            }
        });
        getContentPane().add(TxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 100, -1));

        TglWaktuFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TglWaktuFormatActionPerformed(evt);
            }
        });
        getContentPane().add(TglWaktuFormat, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 140, -1));

        Catatantxt.setColumns(20);
        Catatantxt.setRows(5);
        catatan.setViewportView(Catatantxt);

        getContentPane().add(catatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 140, 60));

        Createbtn.setText("CREATE");
        Createbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Createbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        Deletebtn.setText("DELETE");
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        Updatebtn.setText("UPDATE");
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        Exitbtn.setText("EXIT");
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        Caritxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaritxtActionPerformed(evt);
            }
        });
        getContentPane().add(Caritxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 250, -1));

        Searchbtn.setText("SEARCH");
        Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\pa\\src\\image\\peminjaman (1) (1).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        modeltabelpeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Peminjaman", "Tanggal Peminjaman", "Catatan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        modeltabelpeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modeltabelpeminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(modeltabelpeminjaman);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 337, 600, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdActionPerformed
    
    
    
    private void CreatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatebtnActionPerformed
        Peminjaman.create();
        Peminjaman.isitable();
        Peminjaman.reset();
    }//GEN-LAST:event_CreatebtnActionPerformed

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        Peminjaman.update();
        Peminjaman.isitable();
        Peminjaman.reset();
    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
        menu menu = new menu();
        menu.setVisible(true);
    }//GEN-LAST:event_ExitbtnActionPerformed

    private void TglWaktuFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TglWaktuFormatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TglWaktuFormatActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        Peminjaman.delete();
        Peminjaman.isitable();
        Peminjaman.reset();
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void modeltabelpeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modeltabelpeminjamanMouseClicked
        Peminjaman.isiField(modeltabelpeminjaman.getSelectedRow());
    }//GEN-LAST:event_modeltabelpeminjamanMouseClicked

    private void CaritxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaritxtActionPerformed
        
    }//GEN-LAST:event_CaritxtActionPerformed

    private void SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbtnActionPerformed
        String cari = Caritxt.getText();
        Peminjaman.cariID(cari);
    }//GEN-LAST:event_SearchbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new peminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Caritxt;
    private javax.swing.JTextArea Catatantxt;
    private javax.swing.JButton Createbtn;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JButton Exitbtn;
    private javax.swing.JButton Searchbtn;
    private javax.swing.JFormattedTextField TglWaktuFormat;
    private javax.swing.JTextField TxtId;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JScrollPane catatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable modeltabelpeminjaman;
    // End of variables declaration//GEN-END:variables

    public JTextField getCaritxt() {
        return Caritxt;
    }

    public JTextArea getCatatantxt() {
        return Catatantxt;
    }

    public JButton getCreatebtn() {
        return Createbtn;
    }

    public JButton getDeletebtn() {
        return Deletebtn;
    }

    public JButton getSearchbtn() {
        return Searchbtn;
    }

    public JFormattedTextField getTglWaktuFormat() {
        return TglWaktuFormat;
    }

    public JTextField getTxtId() {
        return TxtId;
    }

    public JButton getUpdatebtn() {
        return Updatebtn;
    }

    public JScrollPane getCatatan() {
        return catatan;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTable getModeltabelpeminjaman() {
        return modeltabelpeminjaman;
    }

    

}
    
